development: &BASE
  adapter: mysql2
  database: ems_dev
  username: root
  password: redhat
  host: 127.0.0.1
  timeout: 5000

test: &test
  <<: *BASE
  database: ems_test

production:
  <<: *BASE
  database: ems_production

cucumber:
  <<: *test